### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by thieman** [uber-common/node-kafka-rest-client#48]
Hi there, just wondering whether this project could be considered ready for use or if it's still a prototype. It looks like it has some appealing features over Confluent's Node driver (retry, chiefly) so I'd love to try it out if it makes sense.

**Comment by mmchen** [comment]
This lib is being used at Uber in many projects, but is depends on the Uber setup of Kafka rest proxy, so you cannot simply use this lib out of the box. You may want to try it out once we release Uber's Kafka rest proxy code.
