### ISSUE TITLE
Builds are broken on master

### ISSUE THREAD

**Issue by akshayjshah** [uber-common/node-kafka-rest-client#52]
Recent PRs haven't had passing builds when they were merged, and now builds are broken on master: https://travis-ci.org/uber-common/node-kafka-rest-client/builds.

**Comment by dongxiaoman** [comment]
It is broken due to `formatio` cannot be found.
Local `npm` and tests are all fine.

**Comment by dongxiaoman** [comment]
@akshayjshah do you have any suggestion on how to fix/debug such server side package installation errors? It was broken for a while

**Comment by akshayjshah** [comment]
I haven't looked at the failure in detail; this is (presumably) your team's project, so you own the CI and build process. If you're not sure what to do, please escalate within the streaming team or the larger data engineering org.

**Comment by dongxiaoman** [comment]
Fixed finally.
